/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dursneakers;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import vistas.settingConexion;

/**
 *
 * @author leiderp
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    private boolean a = true;
    private int x;
    private int y;
    settingConexion paneConexion = new settingConexion();
    CambiaPanel cambiar = new CambiaPanel();
    public mainMenu() {
        initComponents();
        this.setExtendedState(mainMenu.MAXIMIZED_BOTH);
        AWTUtilities.setWindowOpaque(this, false);
        //this.setLocationRelativeTo(null);
        try{
            for (UIManager.LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e){}
    }
    
    class FONDOPANEL extends JPanel{
        private Image image;
        @Override
        public void paint(Graphics g){
            image = new ImageIcon(getClass().getResource("/Icon/logo.jpeg")).getImage();
            g.drawImage(image, 0, 0, getWidth(),getHeight(),this);
            g.drawRoundRect(WIDTH, WIDTH, WIDTH, HEIGHT, WIDTH, HEIGHT);
            setOpaque(false);
            super.paint(g);
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        iconClose = new javax.swing.JPanel();
        buttonClose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        buttonMin = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        buttonMax = new javax.swing.JPanel();
        fullMax = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        lineHideMenu = new javax.swing.JPanel();
        hideMenu = new javax.swing.JPanel();
        buttonHideMenu = new javax.swing.JLabel();
        lineSetting = new javax.swing.JPanel();
        setting = new javax.swing.JPanel();
        buttonSetting = new javax.swing.JLabel();
        menuHiden = new javax.swing.JPanel();
        jPanel3 = new FONDOPANEL();
        jScrollPane1 = new javax.swing.JScrollPane();
        dashView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        header.setBackground(new java.awt.Color(74, 35, 90));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setLayout(new java.awt.BorderLayout());

        iconClose.setBackground(new java.awt.Color(74, 35, 90));
        iconClose.setPreferredSize(new java.awt.Dimension(150, 50));
        iconClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClose.setBackground(new java.awt.Color(74, 35, 90));
        buttonClose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        buttonClose.add(close, java.awt.BorderLayout.CENTER);

        iconClose.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        buttonMin.setBackground(new java.awt.Color(74, 35, 90));
        buttonMin.setLayout(new java.awt.BorderLayout());

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        buttonMin.add(minimize, java.awt.BorderLayout.CENTER);

        iconClose.add(buttonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        buttonMax.setBackground(new java.awt.Color(74, 35, 90));
        buttonMax.setLayout(new java.awt.BorderLayout());

        fullMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/full_screen_32px.png"))); // NOI18N
        fullMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullMaxMouseExited(evt);
            }
        });
        buttonMax.add(fullMax, java.awt.BorderLayout.CENTER);

        iconClose.add(buttonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        header.add(iconClose, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(74, 35, 90));
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(74, 35, 90));
        logo.setPreferredSize(new java.awt.Dimension(50, 50));
        logo.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logod.jpeg"))); // NOI18N
        logo.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jPanel7.setBackground(new java.awt.Color(74, 35, 90));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Vivaldi", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DurSneakers");
        jPanel7.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 50));

        header.add(jPanel2, java.awt.BorderLayout.LINE_START);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(270, 450));
        menu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(74, 35, 90));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineHideMenu.setBackground(new java.awt.Color(74, 35, 90));
        lineHideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineHideMenuLayout = new javax.swing.GroupLayout(lineHideMenu);
        lineHideMenu.setLayout(lineHideMenuLayout);
        lineHideMenuLayout.setHorizontalGroup(
            lineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineHideMenuLayout.setVerticalGroup(
            lineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(lineHideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 5));

        hideMenu.setBackground(new java.awt.Color(74, 35, 90));
        hideMenu.setLayout(new java.awt.BorderLayout());

        buttonHideMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonHideMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back_32px.png"))); // NOI18N
        buttonHideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHideMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonHideMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonHideMenuMouseExited(evt);
            }
        });
        hideMenu.add(buttonHideMenu, java.awt.BorderLayout.CENTER);

        menuIcon.add(hideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        lineSetting.setBackground(new java.awt.Color(74, 35, 90));
        lineSetting.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineSettingLayout = new javax.swing.GroupLayout(lineSetting);
        lineSetting.setLayout(lineSettingLayout);
        lineSettingLayout.setHorizontalGroup(
            lineSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineSettingLayout.setVerticalGroup(
            lineSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        menuIcon.add(lineSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 5));

        setting.setBackground(new java.awt.Color(74, 35, 90));
        setting.setLayout(new java.awt.BorderLayout());

        buttonSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/settings_32px.png"))); // NOI18N
        buttonSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSettingMouseExited(evt);
            }
        });
        setting.add(buttonSetting, java.awt.BorderLayout.CENTER);

        menuIcon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, 50));

        menu.add(menuIcon, java.awt.BorderLayout.LINE_START);

        menuHiden.setBackground(new java.awt.Color(91, 44, 111));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout menuHidenLayout = new javax.swing.GroupLayout(menuHiden);
        menuHiden.setLayout(menuHidenLayout);
        menuHidenLayout.setHorizontalGroup(
            menuHidenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuHidenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuHidenLayout.setVerticalGroup(
            menuHidenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuHidenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );

        menu.add(menuHiden, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        dashView.setBackground(new java.awt.Color(187, 143, 206));
        dashView.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(dashView);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    private void changeColor(JPanel hover,Color rand){
    hover.setBackground(rand);
    }
    
    private void clickMenu(JPanel h1,JPanel h2){
        h1.setBackground(new Color(187, 143, 206));
        h2.setBackground(new Color(74,35,90));
        
    }
    
    private int closing(){
    int seleccion = JOptionPane.showOptionDialog(null,"Desea  Salir?", null,JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE,null,new Object[] { "SI", "NO"}, "SI");
    return seleccion;
    }
    
    private void hideShow(JPanel menuShowHide, boolean dash,JLabel button){
        if (dash==true) {
            menuShowHide.setPreferredSize(new Dimension(50,menuShowHide.getHeight()));
            changeImage(button,"/Icon/menu_32px.png");
        }else{
            menuShowHide.setPreferredSize(new Dimension(270,menuShowHide.getHeight()));
            changeImage(button,"/Icon/back_32px.png");
        }
    }
    
    private void changeImage(JLabel button,String resourceImg){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourceImg));
        button.setIcon(aimg);
    }
    
    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        changeColor(buttonClose,new Color(255, 0, 0));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        changeColor(buttonClose,new Color(74,35,90));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        if (closing()==0) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeMouseClicked

    private void fullMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseEntered
        // TODO add your handling code here:
        changeColor(buttonMax,new Color(187, 143, 206));
    }//GEN-LAST:event_fullMaxMouseEntered

    private void fullMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseExited
        // TODO add your handling code here:
        changeColor(buttonMax,new Color(74,35,90));
    }//GEN-LAST:event_fullMaxMouseExited
    
    private void fullMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseClicked
        // TODO add your handling code here:
        if (this.getExtendedState() != mainMenu.MAXIMIZED_BOTH) {
            this.setExtendedState(mainMenu.MAXIMIZED_BOTH);
        }else{
        this.setExtendedState(mainMenu.NORMAL);
        }
    }//GEN-LAST:event_fullMaxMouseClicked

    private void buttonHideMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHideMenuMouseEntered
        // TODO add your handling code here:
        changeColor(lineHideMenu,new Color(255, 0, 0));
    }//GEN-LAST:event_buttonHideMenuMouseEntered

    private void buttonHideMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHideMenuMouseExited
        // TODO add your handling code here:
        changeColor(lineHideMenu,new Color(74,35,90));
    }//GEN-LAST:event_buttonHideMenuMouseExited

    private void buttonHideMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHideMenuMouseClicked
        // TODO add your handling code here:
        //otro pane2 = new otro();
        //pane2.setVisible(true);
        //dashView.add(pane2);
        clickMenu(hideMenu,setting);
        if (a==true) {
            hideShow(menu,a,buttonHideMenu);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;
        }else{
            hideShow(menu,a,buttonHideMenu);
            SwingUtilities.updateComponentTreeUI(this);
            a = true;
        }
        
    }//GEN-LAST:event_buttonHideMenuMouseClicked

    private void buttonSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSettingMouseEntered
        // TODO add your handling code here:
        changeColor(lineSetting,new Color(130, 224, 170));
    }//GEN-LAST:event_buttonSettingMouseEntered

    private void buttonSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSettingMouseExited
        // TODO add your handling code here:
        changeColor(lineSetting,new Color(74,35,90));
    }//GEN-LAST:event_buttonSettingMouseExited

    private void buttonSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSettingMouseClicked
        // TODO add your handling code here:
        clickMenu(setting,hideMenu);
        cambiar.cambiarPanel(dashView,paneConexion);
        //pane1.setVisible(true);
        //pane2.setVisible(false);
        //dashView.add(pane1);
    }//GEN-LAST:event_buttonSettingMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        changeColor(buttonMin,new Color(187, 143, 206));
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
        changeColor(buttonMin,new Color(74,35,90));
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(mainMenu.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonClose;
    private javax.swing.JLabel buttonHideMenu;
    private javax.swing.JPanel buttonMax;
    private javax.swing.JPanel buttonMin;
    private javax.swing.JLabel buttonSetting;
    private javax.swing.JLabel close;
    private javax.swing.JPanel dashView;
    private javax.swing.JLabel fullMax;
    private javax.swing.JPanel header;
    private javax.swing.JPanel hideMenu;
    private javax.swing.JPanel iconClose;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lineHideMenu;
    private javax.swing.JPanel lineSetting;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuHiden;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel setting;
    // End of variables declaration//GEN-END:variables
}
